"""Generate a TunerPro XDF for the MK60E5 1M application image (7846411A).

Load the XDF against flash/bin/7846411A_00000000.bin (1 MiB, file offset = .0pa address).
Everything below is written in CPU addresses; XDF addresses = CPU + APP_OFFSET (0x8000).

Usage:  python tools/make_xdf.py flash/bin/7846411A_00000000.bin -o xdf/MK60E5_7846411A.xdf
"""
import argparse
import datetime
import pathlib
import struct
from xml.sax.saxutils import escape, quoteattr

APP_OFFSET = 0x8000  # bin offset = CPU address + APP_OFFSET

VBR = 0x40000
CAN_HDR, CAN_MSG, CAN_MSG_SIZE = 0xD82D5, 0xD82F5, 23
CAN_SIG_SIZE, CAN_VAR, CAN_VAR_SIZE = 5, 0xD8C34, 8
KWP_SERVICES, KWP_SERVICE_SIZE = 0xF33A8, 12
CAL_DIR = 0x40300
OS_STACK_TOP, OS_STACK_BOTTOM, OS_TASK_ENTRY = 0x426D8, 0x426EC, 0x42700
OS_TASK_PRIO, OS_TASK_AUTOSTART, OS_SLOT_TABLE = 0x42714, 0x42734, 0x70B28

VECTOR_NAMES = {0: "reset", 1: "misaligned", 2: "access error", 3: "divide by zero", 4: "illegal",
                5: "privilege", 6: "trace", 7: "breakpoint", 8: "unrecoverable", 9: "soft reset",
                10: "INT autovector", 11: "FINT autovector", 12: "HW accelerator",
                16: "trap 0", 17: "trap 1", 18: "trap 2", 19: "trap 3",
                56: "WSS edge ch3 (D8 +9E)", 57: "WSS edge ch1 (F8 +9E)",
                58: "WSS edge ch2 (D8 +8E)", 59: "WSS edge ch0 (F8 +8E)"}

OUT_FLOAT, OUT_INT, OUT_HEX = 1, 2, 3


class Xdf:
    def __init__(self):
        self.items = []
        self.uid = 0x100
        self.categories = []

    def category(self, name):
        self.categories.append(name)
        return len(self.categories)  # CATEGORYMEM is 1-based

    def _next(self):
        self.uid += 1
        return self.uid

    def constant(self, cat, title, cpu_addr, bits, desc="", units="", eq="X", decimals=0,
                 signed=False, out=OUT_FLOAT):
        flags = 0x1 if signed else 0x0
        self.items.append(f"""  <XDFCONSTANT uniqueid="{self._next():#x}">
    <title>{escape(title)}</title>
    <description>{escape(desc)}</description>
    <CATEGORYMEM index="0" category="{cat}" />
    <EMBEDDEDDATA mmedtypeflags="{flags:#04x}" mmedaddress="{cpu_addr + APP_OFFSET:#x}" mmedelementsizebits="{bits}" mmedmajorstridebits="0" mmedminorstridebits="0" />
    <units>{escape(units)}</units>
    <decimalpl>{decimals}</decimalpl>
    <outputtype>{out}</outputtype>
    <datatype>0</datatype>
    <unittype>0</unittype>
    <DALINK index="0" />
    <MATH equation={quoteattr(eq)}>
      <VAR id="X" />
    </MATH>
  </XDFCONSTANT>""")

    def column(self, cat, title, cpu_addr, bits, rows, stride_bytes, labels, desc="", units="",
               eq="X", decimals=0, signed=False, out=OUT_FLOAT):
        """One value per row, rows `stride_bytes` apart (struct-array field)."""
        flags = 0x1 if signed else 0x0
        lab = "\n".join(f'      <LABEL index="{i}" value={quoteattr(l)} />' for i, l in enumerate(labels))
        self.items.append(f"""  <XDFTABLE uniqueid="{self._next():#x}" flags="0x0">
    <title>{escape(title)}</title>
    <description>{escape(desc)}</description>
    <CATEGORYMEM index="0" category="{cat}" />
    <XDFAXIS id="x" uniqueid="0x0">
      <EMBEDDEDDATA mmedelementsizebits="8" mmedmajorstridebits="0" mmedminorstridebits="0" />
      <indexcount>1</indexcount>
      <datatype>0</datatype>
      <unittype>0</unittype>
      <DALINK index="0" />
      <LABEL index="0" value="value" />
      <MATH equation="X">
        <VAR id="X" />
      </MATH>
    </XDFAXIS>
    <XDFAXIS id="y" uniqueid="0x0">
      <EMBEDDEDDATA mmedelementsizebits="8" mmedmajorstridebits="0" mmedminorstridebits="0" />
      <indexcount>{rows}</indexcount>
      <datatype>0</datatype>
      <unittype>0</unittype>
      <DALINK index="0" />
{lab}
      <MATH equation="X">
        <VAR id="X" />
      </MATH>
    </XDFAXIS>
    <XDFAXIS id="z">
      <EMBEDDEDDATA mmedtypeflags="{flags:#04x}" mmedaddress="{cpu_addr + APP_OFFSET:#x}" mmedelementsizebits="{bits}" mmedrowcount="{rows}" mmedcolcount="1" mmedmajorstridebits="{stride_bytes * 8}" mmedminorstridebits="0" />
      <units>{escape(units)}</units>
      <decimalpl>{decimals}</decimalpl>
      <outputtype>{out}</outputtype>
      <MATH equation={quoteattr(eq)}>
        <VAR id="X" />
      </MATH>
    </XDFAXIS>
  </XDFTABLE>""")

    def render(self, title, desc, size):
        cats = "\n".join(f'    <CATEGORY index="{i:#x}" name={quoteattr(n)} />' for i, n in enumerate(self.categories))
        return f"""<!-- Generated by tools/make_xdf.py on {datetime.date.today()} -->
<XDFFORMAT version="1.70">
  <XDFHEADER>
    <flags>0x1</flags>
    <fileversion>0.1</fileversion>
    <deftitle>{escape(title)}</deftitle>
    <description>{escape(desc)}</description>
    <author>e92_mk60e5 RE</author>
    <BASEOFFSET offset="0" subtract="0" />
    <DEFAULTS datasizeinbits="8" sigdigits="2" outputtype="1" signed="0" lsbfirst="0" float="0" />
    <REGION type="0xFFFFFFFF" startaddress="0x0" size="{size:#x}" regionflags="0x0" name="Binary File" desc="7846411A_00000000.bin" />
{cats}
  </XDFHEADER>
{chr(10).join(self.items)}
</XDFFORMAT>
"""


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("image")
    ap.add_argument("-o", "--out", type=pathlib.Path, required=True)
    args = ap.parse_args()
    data = open(args.image, "rb").read()

    def b(cpu, n=1):
        o = cpu + APP_OFFSET
        return data[o:o + n]

    def u16(cpu):
        return struct.unpack(">H", b(cpu, 2))[0]

    def u32(cpu):
        return struct.unpack(">I", b(cpu, 4))[0]

    x = Xdf()
    c_info = x.category("Info / vectors")
    c_tx = x.category("CAN TX messages")
    c_rx = x.category("CAN RX messages")
    c_sig = x.category("CAN signals")
    c_var = x.category("CAN variables")
    c_cal = x.category("Calibration blocks")
    c_os = x.category("OS")
    c_diag = x.category("Diagnostics")
    c_wss = x.category("Wheel speed")
    c_asic = x.category("Wheel-speed ASIC")
    c_slip = x.category("ABS/TCS slip & decel targets")

    # Vector table
    labels = [f"{i:3d} {VECTOR_NAMES.get(i, 'irq' if i >= 32 else 'reserved')}" for i in range(128)]
    x.column(c_info, "Vector table (handler address, bit0 = alt reg file)", VBR, 32, 128, 4, labels,
             desc="M-CORE vector table at VBR=0x40000 (set at CPU 0x06CA18). CPU addresses.",
             out=OUT_HEX)

    # CAN messages
    n_tx, n_rx = b(CAN_HDR + 0x10)[0], b(CAN_HDR + 0x11)[0]
    sig_tab = 0xD82E2 + u16(CAN_HDR + 0x0C)
    msg_ids = [u16(CAN_MSG + CAN_MSG_SIZE * i + 2) for i in range(n_tx + n_rx)]
    for cat, first, count, tag in ((c_tx, 0, n_tx, "TX"), (c_rx, n_tx, n_rx, "RX")):
        base = CAN_MSG + CAN_MSG_SIZE * first
        lab = [f"0x{msg_ids[first + i]:03X}" for i in range(count)]
        common = dict(rows=count, stride_bytes=CAN_MSG_SIZE, labels=lab)
        x.column(cat, f"{tag} CAN id", base + 2, 16, out=OUT_HEX, desc="11-bit identifier", **common)
        x.column(cat, f"{tag} flags|DLC", base + 4, 8, out=OUT_HEX,
                 desc="High nibble = flags, low nibble = DLC", **common)
        x.column(cat, f"{tag} period", base + 6, 8, units="ms", eq="X*10",
                 desc="Cycle time in 10 ms units; 255 (2550) = event / no timeout", **common)
        x.column(cat, f"{tag} signal count", base + 10, 8, **common)
        x.column(cat, f"{tag} first signal", base + 11, 16, **common)
        x.column(cat, f"{tag} mailbox", base + 13, 8, desc="Hardware message buffer 0-31", **common)

    # CAN signals
    owner = {}
    for i, cid in enumerate(msg_ids):
        m = CAN_MSG + CAN_MSG_SIZE * i
        n, f = b(m + 10)[0], u16(m + 11)
        for s in range(f, f + n):
            owner[s] = f"{'TX' if i < n_tx else 'RX'} 0x{cid:03X}"
    n_sig = max(owner) + 1
    lab = [f"{s:3d} {owner.get(s, '?')}" for s in range(n_sig)]
    common = dict(rows=n_sig, stride_bytes=CAN_SIG_SIZE, labels=lab)
    x.column(c_sig, "Signal flags|bit length", sig_tab, 8, out=OUT_HEX,
             desc="Low 5 bits = length in bits, top 3 bits = flags", **common)
    x.column(c_sig, "Signal position", sig_tab + 1, 8, out=OUT_HEX,
             desc="Low nibble = start byte, high nibble = start bit", **common)
    x.column(c_sig, "Signal variable id", sig_tab + 3, 16, out=OUT_HEX, **common)

    # CAN variables
    n_var = max(u16(sig_tab + CAN_SIG_SIZE * s + 3) for s in range(n_sig)) + 1
    lab = [f"0x{v:03X}" for v in range(n_var)]
    common = dict(rows=n_var, stride_bytes=CAN_VAR_SIZE, labels=lab)
    x.column(c_var, "Variable type", CAN_VAR, 8, desc="Low 3 bits: 2/4 = special handling in 0x079D24",
             **common)
    x.column(c_var, "Variable default", CAN_VAR + 1, 8, out=OUT_HEX, **common)
    x.column(c_var, "Variable callback", CAN_VAR + 4, 32, out=OUT_HEX,
             desc="Getter (TX) / setter (RX) function, CPU address", **common)

    # Calibration block directory (0x40300) and raw views of each block
    n_blk = u32(CAL_DIR + 4)
    blocks = [(b(CAL_DIR + 12 + 12 * i, 4).rstrip(b"\0").decode(), u32(CAL_DIR + 16 + 12 * i),
               u32(CAL_DIR + 20 + 12 * i)) for i in range(n_blk)]
    lab = [t for t, _, _ in blocks]
    x.column(c_cal, "Calibration directory: block address", CAL_DIR + 16, 32, n_blk, 12, lab, out=OUT_HEX)
    x.column(c_cal, "Calibration directory: block length", CAL_DIR + 20, 32, n_blk, 12, lab)
    for tag, addr, length in blocks:
        n = (length - 12) // 2
        x.column(c_cal, f"{tag} block raw data (u16)", addr + 12, 16, n, 2,
                 [f"+0x{12 + 2 * i:03X}" for i in range(n)], out=OUT_HEX,
                 desc=f"Raw view of calibration block {tag} at {addr:#x} (len {length:#x}); field "
                      "meanings not decoded. Covered by the ROM self-test range [0x40300, 0x426BC).")

    # OS configuration
    tasks = ["T0 (event, autostart)", "T1", "T2", "T3", "T4 (background)"]
    x.column(c_os, "OS task entry", OS_TASK_ENTRY, 32, 5, 4, tasks, out=OUT_HEX)
    x.column(c_os, "OS task priority (0 = highest)", OS_TASK_PRIO, 16, 5, 2, tasks)
    x.column(c_os, "OS task autostart", OS_TASK_AUTOSTART, 8, 5, 1, tasks)
    x.column(c_os, "OS task stack top", OS_STACK_TOP, 32, 5, 4, tasks, out=OUT_HEX)
    x.column(c_os, "OS task stack bottom", OS_STACK_BOTTOM, 32, 5, 4, tasks, out=OUT_HEX)
    x.column(c_os, "Time-base slot handlers (vec60)", OS_SLOT_TABLE, 32, 13, 4,
             [f"slot {i}" for i in range(13)], out=OUT_HEX,
             desc="Jump table used by isr_timeslot 0x070A86; one entry per 13-slot frame position")

    # Diagnostics (KWP2000 service dispatch)
    n_srv = 23
    lab = [f"SID 0x{b(KWP_SERVICES + KWP_SERVICE_SIZE * i)[0]:02X}" for i in range(n_srv)]
    common = dict(rows=n_srv, stride_bytes=KWP_SERVICE_SIZE, labels=lab)
    x.column(c_diag, "KWP2000 service id", KWP_SERVICES, 8, out=OUT_HEX, **common)
    x.column(c_diag, "KWP2000 service min length", KWP_SERVICES + 1, 8,
             desc="Minimum request length; 255 = not checked here", **common)
    x.column(c_diag, "KWP2000 service handler", KWP_SERVICES + 4, 32, out=OUT_HEX,
             desc="Handler function, CPU address", **common)
    x.column(c_diag, "KWP2000 service flags", KWP_SERVICES + 8, 16, out=OUT_HEX, **common)

    # Wheel speed: BFU calibration block (tag "BFU\x01" at 0x41F04)
    bfu = "BFU block at 0x41F04. "
    x.constant(c_wss, "BFU 0x41F10 (unknown, no reader found)", 0x41F10, 16, desc=bfu)
    x.constant(c_wss, "Standstill threshold", 0x41F12, 16, units="km/h", eq="X/100", decimals=2,
               signed=True, desc=bfu + "Wheel counted as standstill below this (count_standstill_wheels 0x071D1C).")
    x.constant(c_wss, "Wheel circumference front", 0x41F14, 16, units="mm",
               desc=bfu + "Used by wheel_cal_prepare 0x075204 (900*C) for wheels 0/1. Unit assumed mm.")
    x.constant(c_wss, "Wheel circumference rear", 0x41F16, 16, units="mm",
               desc=bfu + "Used for wheels 2/3. Unit assumed mm.")
    x.constant(c_wss, "Tone wheel teeth front", 0x41F18, 16, desc=bfu + "Agent reading: tooth count. "
               "Tooth-correction code (0xA6xxx-0xAAxxx) also hard-codes 48.")
    x.constant(c_wss, "Tone wheel teeth rear", 0x41F1A, 16, desc=bfu)

    # Wheel speed: direction logic literals (each used only inside wheel_direction_update 0x0B9118)
    dl = "Literal-pool word used only inside wheel_direction_update 0x0B9118. "
    for addr, title, desc in (
            (0xB9450, "Direction logic upper speed", "Direction evaluated below this (used 3x)."),
            (0xB9484, "Direction-invalid window start", "Invalid counter runs for start <= v < start+span."),
            (0xB9488, "Direction-invalid window span", ""),
            (0xB9504, "Direction-mismatch window start", "Stored vs sensor direction compared in this window."),
            (0xB9508, "Direction-mismatch window span", ""),
            (0xB950C, "High-speed forward check speed", "Above this, direction must be forward."),
            (0xB9510, "High-speed forward check ref speed", "Reference-wheel speed condition for the check above.")):
        x.constant(c_wss, title, addr, 32, units="km/h", eq="X/100", decimals=2, desc=dl + desc)
    x.constant(c_wss, "Direction reporting max wheel speed", 0xB95B4, 32, units="km/h",
               eq="X/100", decimals=2,
               desc="Literal used by wheel_direction_valid (0x0B9524): direction is only reported "
                    "when wheel speed <= this. Stock 7000 = 70.00 km/h.")
    x.constant(c_wss, "Wheel speed cap", 0x75590, 32, units="km/h", eq="X/100", decimals=2,
               desc="Literal in wheel_speed_update 0x0752B8 area (agent: cap 30000).")
    wheels = ["w0 front (FL?)", "w1 front (FR?)", "w2 rear (RL?)", "w3 rear (RR?)"]
    x.column(c_wss, "Direction fault id per wheel", 0xF5A74, 32, 4, 4, wheels, out=OUT_HEX,
             desc="Logged via 0x0B4064 after 175 invalid-direction counts")
    x.column(c_wss, "ASIC reply index -> wheel", 0xD79F8, 8, 4, 1, wheels)
    x.column(c_wss, "Direction invert wheel mask", 0xD79FC, 8, 2, 1,
             ["0x4031F4 bit8 = 0", "0x4031F4 bit8 = 1"], out=OUT_HEX,
             desc="Bit per wheel: invert the ASIC direction bit")

    # Sensor-interface ASIC (QSPI chip select 5) init and poll tables
    x.column(c_asic, "ASIC init words", 0xD75A0, 32, 12, 4, [f"{i}" for i in range(12)],
             out=OUT_HEX, desc="Sent by asic_init 0x06F78A..; count byte at 0xD75D0")
    x.column(c_asic, "ASIC init pair: register", 0xD75D2, 16, 13, 4, [f"{i}" for i in range(13)],
             out=OUT_HEX, desc="Count byte at 0xD7606")
    x.column(c_asic, "ASIC init pair: value", 0xD75D4, 16, 13, 4, [f"{i}" for i in range(13)], out=OUT_HEX)
    x.column(c_asic, "ASIC wheel read commands", 0xD7792, 16, 9, 2,
             ["w0", "-", "w1", "-", "w2", "-", "w3", "-", "end"], out=OUT_HEX,
             desc="Polled by asic_sensor_poll 0x06FD70; replies land in 0x400F1C")

    # ABS / TCS decoded slip & deceleration targets (verified; see analysis/agents/{abs,tcs}/REPORT.md).
    # ABS block base 0x4039C, TCS block base 0x40AB8. ABS values are the slip/decel ESTIMATION layer
    # (readers 0x44000-0x5E000), not the valve control; TCS is the rear-axle drive-slip controller.
    ABS, TCS = 0x4039C, 0x40AB8
    gnote = ("ABS deceleration-threshold builder (fn 0x47DFC). Unit ~0.01 g is an UNPROVEN agent guess; "
             "value is signed. ")
    x.constant(c_slip, "ABS decel threshold base", ABS + 0xCC, 16, signed=True, desc=gnote + "Stock -116.")
    x.constant(c_slip, "ABS decel threshold floor", ABS + 0xCA, 16, signed=True, desc=gnote + "Stock -240.")
    x.constant(c_slip, "ABS decel floor <20 km/h", ABS + 0xF0, 16, signed=True, desc=gnote + "Stock -120.")
    x.constant(c_slip, "ABS decel floor <60 km/h", ABS + 0xF2, 16, signed=True, desc=gnote + "Stock -132.")
    x.constant(c_slip, "ABS accel gain front", ABS + 0xC6, 16, signed=True, desc=gnote + "Stock 40.")
    x.constant(c_slip, "ABS accel gain rear", ABS + 0xC8, 16, signed=True, desc=gnote + "Stock 25.")
    x.column(c_slip, "ABS decel ladder", ABS + 0x2C8, 16, 6, 2, [f"{i}" for i in range(6)], signed=True,
             desc="fn 0x55D44/0x56B96. Stock -140,-90,-40,-210,-350,-490 (~0.01 g, unproven).")
    x.column(c_slip, "ABS staged threshold set A", ABS + 0x61E, 16, 3, 2, ["s1", "s2", "s3"], signed=True,
             desc="Three-stage slip-like threshold (fn 0x5444C); set chosen by flag +0x65C. Stock -62,-78,-94.")
    x.column(c_slip, "ABS staged threshold set B", ABS + 0x65E, 16, 3, 2, ["s1", "s2", "s3"], signed=True,
             desc="Stock -25,-44,-62.")
    x.column(c_slip, "ABS staged output", ABS + 0x624, 16, 3, 2, ["s1", "s2", "s3"],
             desc="Stock 1000,1500,2000.")
    for off, title, stock in ((0x458, "ABS speed gate A", 7000), (0x502, "ABS speed gate B", 7000),
                              (0x508, "ABS speed gate C", 10000)):
        x.constant(c_slip, title, ABS + off, 16, signed=True, units="km/h", eq="X/100", decimals=2,
                   desc=f"Per-wheel speed gate. Stock {stock}.")
    x.constant(c_slip, "ABS vref gate 60", ABS + 0x3A6, 16, signed=True, units="km/h", eq="X/100",
               decimals=2, desc="Stock 6000 = 60 km/h.")
    x.constant(c_slip, "ABS vref gate 20", ABS + 0x3A8, 16, signed=True, units="km/h", eq="X/100",
               decimals=2, desc="Stock 2000 = 20 km/h.")
    x.constant(c_slip, "ABS apply ramp per cycle", ABS + 0x0C, 16, signed=True,
               desc="Pressure-level apply ramp (fn 0x44614), capped at 25000. Stock 400.")
    # ABS entry slip-speed threshold curve at ABS+0x576: lo,hi,n, x[n-1], A[n], B[n] (n=2).
    # thr = clamp(A[k] + slip*B[k]/1024, lo, hi); slip = vref - wheel speed, 0.01 km/h (fn 0x54F9A).
    # Split into usable arrays like the TCS curve, not one lumped column.
    snote = "ABS entry/continue slip target (fn 0x54F9A). slip = vref - wheel speed. "
    x.constant(c_slip, "ABS slip threshold clamp max", ABS + 0x578, 16, signed=True, units="km/h",
               eq="X/100", decimals=2, desc=snote + "Upper clamp on the threshold. Stock 900 = 9.00 km/h.")
    x.column(c_slip, "ABS slip threshold breakpoints", ABS + 0x57C, 16, 1, 2, ["x0"], signed=True,
             units="km/h", eq="X/100", decimals=2, desc=snote + "vref segment breakpoint. Stock 5000 = 50 km/h.")
    x.column(c_slip, "ABS slip threshold intercepts A", ABS + 0x57E, 16, 2, 2, ["seg0 <50", "seg1 >=50"],
             signed=True, units="km/h", eq="X/100", decimals=2,
             desc=snote + "Per-segment intercept = the slip target at vref=0 of that segment. Stock 150,115 "
                  "(1.50, 1.15 km/h); with slope the effective target is ~1.3-2.0 km/h.")
    x.column(c_slip, "ABS slip threshold slopes B (Q10)", ABS + 0x582, 16, 2, 2, ["seg0", "seg1"],
             signed=True, eq="X/1024", decimals=4, desc=snote + "Per-segment slope (x*B/1024). Stock -4,3.")

    # TCS drive-slip target: base threshold curve = clamp(A[k] + vref*B[k]/1024). Default = set A mode 0
    # at TCS+0xEC; set B at +0x86; modes 1/2 at +34*m. x is reference speed (min of fronts), 0.01 km/h.
    tnote = ("TCS base DRIVE-SLIP threshold curve, set A mode 0 (default). thr = clamp(A[k] + vref*B[k]/1024, "
             "0, 30000) in 0.01 km/h = allowed rear-minus-front speed difference. Set B at +0x86; "
             "modes 1/2 at +34 bytes each. ")
    x.column(c_slip, "TCS slip curve: breakpoints (A m0)", TCS + 0xF2, 16, 4, 2, [f"x{i}" for i in range(4)],
             signed=True, units="km/h", eq="X/100", decimals=2, desc=tnote + "vref breakpoints; stock 15,25,80,100 km/h.")
    x.column(c_slip, "TCS slip curve: intercepts A (A m0)", TCS + 0xFA, 16, 5, 2, [f"A{i}" for i in range(5)],
             signed=True, units="km/h", eq="X/100", decimals=2, desc=tnote + "Stock 1500,525,-27,-2833,-2138.")
    x.column(c_slip, "TCS slip curve: slopes B Q10 (A m0)", TCS + 0x104, 16, 5, 2, [f"B{i}" for i in range(5)],
             signed=True, eq="X/1024", decimals=3, desc=tnote + "Q10 slopes; stock -840,-174,52,411,340.")
    x.constant(c_slip, "TCS entry hysteresis add", TCS + 0x1DE, 16, signed=True, units="km/h", eq="X/100",
               decimals=2, desc="Added to thr for entry limit (fn 0x0C78D0). Stock 500 = 5.00 km/h.")
    x.constant(c_slip, "TCS exit hysteresis add", TCS + 0x1DC, 16, signed=True, units="km/h", eq="X/100",
               decimals=2, desc="Added to thr for exit limit. Stock 300 = 3.00 km/h.")
    x.column(c_slip, "TCS slip-rate reduction pct", TCS + 0x1D4, 16, 4, 2, [f"p{i}" for i in range(4)],
             signed=True, units="%", desc="R = pct*0x40308E/100 subtracted from limits. Stock 10,10,2,10.")
    x.column(c_slip, "TCS entry gates", TCS + 0x14, 16, 4, 2, ["g0", "g1", "g2", "vref max"], signed=True,
             units="km/h", eq="X/100", decimals=2, desc="Precondition gates (fn 0x0C7BC8). Stock 16,10,20,30 km/h.")
    x.column(c_slip, "TCS gross-slip limit", TCS + 0x0C, 16, 4, 2, ["min", "?", "intercept", "cmp"], signed=True,
             desc="Gross-slip ceiling (fn 0x0C8384): max(+0C, +10 - vref*+0E/1000). Stock 1500,1000,4000,1500.")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(x.render(
        "MK60E5 E82 1M DSC 7846411A (DSCM80) - research",
        "Research definition. Load against flash/bin/7846411A_00000000.bin. XDF address = CPU address "
        "+ 0x8000. Research only. The .0pa $CHECKSUMME is CRC-16/ARC over the data, but the "
        "application is also covered by an in-ECU background ROM self-test (hardware signature unit, "
        "expected values at 0x402F8/0x426BC/0xF6684, algorithm unknown) and a probable 512-bit "
        "signature (BMY block at file 0xFE68C). Do not flash edited images.",
        len(data)), encoding="utf-8")
    print(f"wrote {args.out}: {len(x.items)} items, {n_tx} TX / {n_rx} RX msgs, {n_sig} signals, {n_var} vars")


if __name__ == "__main__":
    main()
